# Generated by Django 4.1.5 on 2023-03-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel2',
        ),
    ]
