# Generated by Django 4.1.5 on 2023-03-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_delete_hotel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('name1', models.CharField(max_length=255)),
                ('name2', models.CharField(max_length=255)),
            ],
        ),
    ]
